// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { db_BundleTable } from "./db_BundleTable";

export interface db_DesignBundleSummary { tables: Array<db_BundleTable>, missingAlleles: Array<string>, }