// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface db_SyncAccount {
  id: string;
  provider: string;
  accountLabel: string;
  remoteListId: string;
  createdAt: string;
  lastSyncedAt: string | null;
}
